# instructions for setting up Travis to work with karma and Chrome taken from:
# http://www.andrewsouthpaw.com/2015/02/12/travis-ci-and-you/

language: node_js
node_js:
  - '0.12'
  - '0.10'
before_install:
  - npm install -g bower
  - npm install -g gulp
install:
  - npm install
before_script:  
  # Special config for Chrome on Travis-CI
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
notifications:  
  email: false
deploy:
  provider: heroku
  api_key:
    secure: DgW2lBxD6URZjwMuuuxuY3KJJTSHALnZhJvqWeKJJhj5tuREAnzS/tx0FQRu/qXf18hJLjtCAJZS36TEz6jp3um2tIXr/9puo04bSdR9nXqc490LM0BvzCmUOjv5d4hJjXGQ50kATg59tITqrsnisaPBWzTjVSlfzBnAFesyFqiSAeHTSyDbMeIMBBxX1zaPE3dzhBUkIdEwnsQe/0OeEfQWhJ+fWQJcN0keqa9rgZfEFsyVKMqWfUpt6kS5nhHtZ1xgq4yi/lHQbbvD4aLtv7gr+WDqjRkWK6x3P7KI1HxO+R9wB4vtOmj6ppo3NeFJu4EeSWTHzuOp9lgCUSTDtV4zkbsn5+6iHxGSqNZwQK0Qs6uUHyYItayl/Zfx0MQBNJ36ccAeq7BKBkK5/3GwCUtlfvIaF2q8r5OpoLo8LQLa5uJeYAydMSF65f32bPpSsZQaF7BaEHYX5oRCUOIFDgwPzZTF0dBb6LdiVUSRpZrzHHMPLYrn9PgDRDU88Dbpc0ls0CkecgDt5025zTEUfdOVh1EUkdO9aor65e3VRuhvEdh0AYud4zfGD9AuI9mY/1f8V17RoCwC3bJ9hY4YUMQ8yxwzEuE9GlRebTHCm3Furtnw9L5tvDu+ckxe/OL+A044cV4UdqONwR+WHTCUXb/9fJd8fSvqWpF2eMCvcJI=
  app: congressmanprofile
