// these are 10 test bills associated with Bernie Sanders
// his list of votes can be found here:
// https://www.govtrack.us/api/v2/vote_voter/?person=400357
// get the id from the property "related_bill"
// and find the fill at https://www.govtrack.us/api/v2/bill/ + bill id

db.billentries.insert({
  "id": "0",
  "bill_id": "341225",
  "terms": [
    "Abortion",
    "Health",
    "Family planning and birth control",
    "Health facilities and institutions",
    "Health programs administration and funding",
    "Sex and reproductive health",
    "Women's health"
  ]
});

db.billentries.insert({
  "id": "1",
  "bill_id": "341222",
  "terms": [
    "Hunting and fishing",
    "Military medicine",
    "Veterans' medical care",
    "Congressional oversight",
    "Law enforcement administration and funding",
    "Appropriations",
    "Budget process",
    "Government trust funds",
    "User charges and fees",
    "Emergency planning and evacuation",
    "Oil and gas",
    "Hazardous wastes and toxic substances",
    "Foreign and international banking",
    "Administrative law and regulatory procedures",
    "Government information and archives",
    "Licensing and registrations",
    "Digestive and metabolic diseases",
    "Disability and paralysis",
    "Health care costs and insurance",
    "Health care coverage and access",
    "Health facilities and institutions",
    "Hospital care",
    "Housing finance and home ownership",
    "Rural conditions and development",
    "Employee benefits and pensions",
    "Research administration and funding",
    "Research and development",
    "Outdoor recreation",
    "Sales and excise taxes",
    "Tax administration and collection, taxpayers",
    "Tax-exempt organizations",
    "Transfer and inheritance taxes",
    "Transportation and Public Works",
    "Aviation and airports",
    "Marine and inland water transportation",
    "Motor carriers",
    "Public transit",
    "Roads and highways",
    "Transportation programs funding",
    "Transportation safety and security",
    "Wetlands",
    "Department of the Treasury"
  ]
});

db.billentries.insert({
  "id": "2",
  "bill_id": "335349",
  "terms": [
    "Hunting and fishing",
    "Insects",
    "Wildlife conservation and habitat protection",
    "Military medicine",
    "Strategic materials and reserves",
    "Veterans' medical care",
    "Consumer affairs",
    "Product safety and quality",
    "Small business",
    "Congressional oversight",
    "Fraud offenses and financial crimes",
    "Appropriations",
    "Government lending and loan guarantees",
    "Government trust funds",
    "Inflation and prices",
    "User charges and fees",
    "Elementary and secondary education",
    "Accidents",
    "Disaster relief and insurance",
    "Emergency planning and evacuation",
    "Electric power generation and transmission",
    "Energy storage, supplies, demand",
    "Hybrid, electric, and advanced technology vehicles",
    "Oil and gas",
    "Air quality",
    "Environmental assessment, monitoring, research",
    "Hazardous wastes and toxic substances",
    "Accounting and auditing",
    "Interest, dividends, interest rates",
    "Life, casualty, property insurance",
    "Competitiveness, trade promotion, trade deficits",
    "Customs enforcement",
    "Administrative law and regulatory procedures",
    "Advisory bodies",
    "Executive agency funding and structure",
    "Government employee pay, benefits, personnel management",
    "Government ethics and transparency, public corruption",
    "Government information and archives",
    "Government studies and investigations",
    "Intergovernmental relations",
    "Licensing and registrations",
    "Performance measurement",
    "Public contracts and procurement",
    "State and local government operations",
    "Comprehensive health care",
    "Drug, alcohol, tobacco use",
    "Health care costs and insurance",
    "Health care coverage and access",
    "Housing finance and home ownership",
    "Regional and metropolitan planning",
    "Rural conditions and development",
    "Visas and passports",
    "Employee benefits and pensions",
    "Civil actions and liability",
    "Indian lands and resources rights",
    "Historic sites and heritage areas",
    "Land use and conservation",
    "Computers and information technology",
    "Research administration and funding",
    "Research and development",
    "Telephone and wireless communication",
    "Outdoor recreation",
    "Sales and excise taxes",
    "Tax administration and collection, taxpayers",
    "Transfer and inheritance taxes",
    "Transportation and Public Works",
    "Aviation and airports",
    "Commuting",
    "Infrastructure development",
    "Marine and inland water transportation",
    "Motor carriers",
    "Motor vehicles",
    "Navigation, waterways, harbors",
    "Pedestrians and bicycling",
    "Pipelines",
    "Public transit",
    "Railroads",
    "Roads and highways",
    "Transportation costs",
    "Transportation programs funding",
    "Transportation safety and security",
    "Water use and supply",
    "Arizona",
    "Export-Import Bank of the United States",
    "Federal Reserve System",
    "Internal Revenue Service (IRS)",
    "National Railroad Passenger Corporation (Amtrak)",
    "Lease and rental services",
    "Department of Energy",
    "Department of the Treasury",
    "Department of Transportation",
    "Debt collection"
  ]
});

db.billentries.insert({
  "id": "3",
  "bill_id": "339105",
  "terms": [
    "Religion",
    "Congressional oversight",
    "Juvenile crime and gang violence",
    "Education",
    "Academic performance and assessments",
    "Adult education and literacy",
    "Education of the disadvantaged",
    "Education programs funding",
    "Educational facilities and institutions",
    "Educational technology and distance education",
    "Elementary and secondary education",
    "Foreign language and bilingual programs",
    "Higher education",
    "Language arts",
    "Minority education",
    "Preschool education",
    "Teaching, teachers, curricula",
    "Adoption and foster care",
    "Domestic violence and child abuse",
    "Administrative law and regulatory procedures",
    "Physical fitness and lifestyle",
    "Homelessness and emergency shelter",
    "Rural conditions and development",
    "Alaska Natives and Hawaiians",
    "Indian social and development programs",
    "Land transfers",
    "Science and engineering education",
    "U.S. history",
    "Department of Education",
    "Educational guidance", 
  ]
});

db.billentries.insert({
  "id": "4",
  "bill_id": "338388",
  "terms": [
    "Fruit and vegetables",
    "Animal protection and human-animal relationships",
    "Birds",
    "Endangered and threatened species",
    "Mammals",
    "Armed Forces and National Security",
    "Alliances",
    "Chemical and biological weapons",
    "Defense spending",
    "Intelligence activities, surveillance, classified information",
    "Military assistance, sales, and agreements",
    "Military education and training",
    "Military facilities and property",
    "Military history",
    "Military law",
    "Military medicine",
    "Military operations and strategy",
    "Military personnel and dependents",
    "Military procurement, research, weapons development",
    "Military readiness",
    "National Guard and reserves",
    "Nuclear weapons",
    "Strategic materials and reserves",
    "Veterans' medical care",
    "Veterans' organizations and recognition",
    "Religion",
    "Detention of persons",
    "Sex, gender, sexual orientation discrimination",
    "Minority and disadvantaged businesses",
    "Small business",
    "Congressional oversight",
    "Assault and harassment offenses",
    "Computer security and identity theft",
    "Crime victims",
    "Criminal procedure and sentencing",
    "Drug trafficking and controlled substances",
    "Firearms and explosives",
    "Organized crime",
    "Sex offenses",
    "Terrorism",
    "Economic development",
    "Academic performance and assessments",
    "Education programs funding",
    "Elementary and secondary education",
    "Alternative and renewable resources",
    "Energy prices",
    "Energy storage, supplies, demand",
    "Oil and gas",
    "Air quality",
    "Climate change and greenhouse gases",
    "Environmental regulatory procedures",
    "Hazardous wastes and toxic substances",
    "Administrative law and regulatory procedures",
    "Advisory bodies",
    "Commemorative events and holidays",
    "Executive agency funding and structure",
    "Federal officials",
    "Government employee pay, benefits, personnel management",
    "Government studies and investigations",
    "Licensing and registrations",
    "Performance measurement",
    "Family planning and birth control",
    "Health care costs and insurance",
    "Health care coverage and access",
    "Health facilities and institutions",
    "Health personnel",
    "Mental health",
    "Prescription drugs",
    "Radiation",
    "Surgery and anesthesia",
    "Women's health",
    "Arab-Israeli relations",
    "Arms control and nonproliferation",
    "Conflicts and wars",
    "Human rights",
    "International law and treaties",
    "International organizations and cooperation",
    "Lawyers and legal services",
    "Historic sites and heritage areas",
    "Land transfers",
    "Marine and coastal resources, fisheries",
    "Research administration and funding",
    "Research and development",
    "Spacecraft and satellites",
    "Aviation and airports",
    "Marine and inland water transportation",
    "Afghanistan",
    "American Samoa",
    "Armed Forces Retirement Home",
    "Asia",
    "Bahrain",
    "California",
    "Caribbean area",
    "Cuba",
    "Defense Nuclear Facilities Safety Board",
    "Department of Defense",
    "District of Columbia",
    "Environmental Protection Agency (EPA)",
    "Estonia",
    "Europe",
    "Florida",
    "Georgia (Republic)",
    "Germany",
    "Guam",
    "Illinois",
    "Iran",
    "Iraq",
    "Israel",
    "Italy",
    "Japan",
    "Jordan",
    "Latin America",
    "Lithuania",
    "Maryland",
    "Middle East",
    "Northern Mariana Islands",
    "Ohio",
    "Oklahoma",
    "Pakistan",
    "Portugal",
    "Russia",
    "Syria",
    "Texas",
    "Turkey",
    "Ukraine",
    "United Kingdom",
    "Service animals",
    "Palestinians",
    "Africa",
    "Department of Energy",
    "Department of Veterans Affairs"
  ]
});

db.billentries.insert({
  "id": "5",
  "bill_id": "337623",
  "terms": [
    "Agricultural trade",
    "Food assistance and relief",
    "Women's rights",
    "Corporate finance and management",
    "Women in business",
    "Congressional oversight",
    "Budget deficits and national debt",
    "Economic development",
    "User charges and fees",
    "Higher education",
    "Student aid and college costs",
    "Foreign Trade and International Finance",
    "Customs enforcement",
    "Tariffs",
    "Trade agreements and negotiations",
    "U.S. and foreign investments",
    "Administrative law and regulatory procedures",
    "Government information and archives",
    "Medicare",
    "Foreign aid and international relief",
    "Women's employment",
    "Administrative remedies",
    "Judicial review and appeals",
    "Outdoor recreation",
    "Income tax credits",
    "Income tax deductions",
    "Tax administration and collection, taxpayers",
    "Tax-exempt organizations",
    "Caribbean area",
    "Haiti",
    "Internal Revenue Service (IRS)",
    "Latin America",
    "Africa",
    "Department of the Treasury"
  ]
});

db.billentries.insert({
  "id": "6",
  "bill_id": "339139",
  "terms": [
    "Agricultural prices, subsidies, credit",
    "Agricultural trade",
    "Food supply, safety, and labeling",
    "Seafood",
    "Endangered and threatened species",
    "Wildlife conservation and habitat protection",
    "Digital media",
    "Religion",
    "Intellectual property",
    "Manufacturing",
    "Service industries",
    "Small business",
    "Congressional committees",
    "Congressional operations and organization",
    "Congressional oversight",
    "Legislative rules and procedure",
    "Law enforcement officers",
    "Economic performance and conditions",
    "Fires",
    "Air quality",
    "Environmental assessment, monitoring, research",
    "Environmental regulatory procedures",
    "Environmental technology",
    "Marine pollution",
    "Water quality",
    "Currency",
    "Foreign Trade and International Finance",
    "Competitiveness, trade promotion, trade deficits",
    "Customs enforcement",
    "Free trade and trade barriers",
    "International monetary system and foreign exchange",
    "Tariffs",
    "Trade agreements and negotiations",
    "Trade restrictions",
    "U.S. and foreign investments",
    "Administrative law and regulatory procedures",
    "Advisory bodies",
    "Executive agency funding and structure",
    "Federal officials",
    "Government employee pay, benefits, personnel management",
    "Government ethics and transparency, public corruption",
    "Government information and archives",
    "Presidents and presidential powers",
    "Public participation and lobbying",
    "State and local government operations",
    "Rural conditions and development",
    "Arab-Israeli relations",
    "Human rights",
    "International organizations and cooperation",
    "Rule of law and government transparency",
    "Sanctions",
    "Sovereignty, recognition, national governance and status",
    "Employee benefits and pensions",
    "Employment discrimination and employee rights",
    "Labor standards",
    "Youth employment and child labor",
    "Marine and coastal resources, fisheries",
    "Internet and video services",
    "Income tax exclusion",
    "Aviation and airports",
    "Wetlands",
    "Asia",
    "Europe",
    "European Union",
    "House Committee on Ways and Means",
    "Israel",
    "Middle East",
    "Office of the U.S. Trade Representative",
    "Senate Committee on Finance",
    "First responders and emergency personnel",
    "Arctic and polar regions"
  ]
});

db.billentries.insert({
  "id": "7",
  "bill_id": "340141",
  "terms": [
    "Armed Forces and National Security",
    "Chemical and biological weapons",
    "Defense spending",
    "Intelligence activities, surveillance, classified information",
    "Military assistance, sales, and agreements",
    "Military operations and strategy",
    "Military personnel and dependents",
    "Military procurement, research, weapons development",
    "Drug trafficking and controlled substances",
    "Appropriations",
    "Executive agency funding and structure",
    "Government employee pay, benefits, personnel management",
    "Arms control and nonproliferation",
    "Foreign aid and international relief",
    "Federal appellate courts",
    "Specialized courts",
    "Research administration and funding",
    "Research and development",
    "Central Intelligence Agency (CIA)",
    "Department of Defense"
  ]
});

db.billentries.insert({
  "id": "8",
  "bill_id": "338927",
  "terms": [
    "Armed Forces and National Security",
    "Chemical and biological weapons",
    "Intelligence activities, surveillance, classified information",
    "Nuclear weapons",
    "Right of privacy",
    "Business records",
    "Congressional oversight",
    "Crimes against animals and natural resources",
    "Criminal investigation, prosecution, interrogation",
    "Criminal procedure and sentencing",
    "Firearms and explosives",
    "Terrorism",
    "Oil and gas",
    "Hazardous wastes and toxic substances",
    "Marine pollution",
    "Pollution liability",
    "Radioactive wastes and releases",
    "Consumer credit",
    "Infectious and parasitic diseases",
    "Arms control and nonproliferation",
    "International law and treaties",
    "Civil actions and liability",
    "Evidence and witnesses",
    "Judicial review and appeals",
    "Jurisdiction and venue",
    "Marine and coastal resources, fisheries",
    "Telephone and wireless communication",
    "Marine and inland water transportation",
    "Navigation, waterways, harbors",
    "Transportation safety and security"
  ]
});

db.billentries.insert({
  "id": "9",
  "bill_id": "339517",
  "terms": [
    "Armed Forces and National Security", 
    "Intelligence activities, surveillance, classified information", 
    "Business records", 
    "Terrorism"
  ]
});
